# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

exclude: thirdparty/
repos:
# Standard hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v6.0.0"
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-json
  - id: check-yaml
    exclude: ".gitlab-ci.yml"
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: "^vcpkg/ports/.*\\.patch$"
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    exclude: "^vcpkg/ports/.*\\.patch$"
  - id: check-ast

# Changes tabs to spaces
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: "v1.5.6"
  hooks:
  - id: remove-tabs

# Clang format the codebase automatically
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: "v22.1.0"
  hooks:
  - id: clang-format
    exclude: "^.*thirdparty/.*$"
    args: ["-style=file"]
    types_or: [c++, c, cuda]
